### PR TITLE
images and transformations

### PR DESCRIPTION
**Pull request by illudedPerception**
* Removed old images to reduce size of Railroad.studio
* Added new rotated images
* Edited code to make them work
* Edited borders to make them fit a litte bit better, not perfect on two maps because of .5 on the transformation size

## Summary by CodeRabbit

- **New Features**
	- Enhanced visual fidelity of the map rendering based on game levels.
	- Improved background and border rendering for 'MesaPlains' and 'AuroraFalls' game levels.

### CODE REVIEW

**Review by scottanderson — CHANGES_REQUESTED** [review]
Thank you for your contribution! I have a few questions and concerns about this PR:

1. Can you clarify why you’re moving the map border? I don't believe this should be changed.
2. I noticed the contrast has been lowered substantially, and I’m not sure this is an improvement. Could you explain your reasoning behind this change?
3. The topo line text is missing from these maps. I thought the plan was to simply rotate them 180 degrees. Making significant changes to the map requires some prior discussion. Please open an issue to propose and discuss any major changes before submitting a PR to ensure alignment and avoid unnecessary work.

**Comment by illudedPerception** [comment]
> 1. Can you clarify why you’re moving the map border? I don't believe this should be changed.

Well they didin't line up with the image edge, what i guess was the idea for them in the first place and the map edges are square so that's why i removed the radius from them.

> 2. I noticed the contrast has been lowered substantially, and I’m not sure this is an improvement. Could you explain your reasoning behind this change?

I only changed the water to be a little bit lighter blue the other blue was too dark in my opinion.

> 3\. The topo line text is missing from these maps. I thought the plan was to simply rotate them 180 degrees. Making significant changes to the map requires some prior discussion. Please open an issue to propose and discuss any major changes before submitting a PR to ensure alignment and avoid unnecessary work.

Just rotating the image would not rotate the numbers and they would be upside down, i had to generate new images.

I removed the numbers cause i don't have height data for Mesa plains, so the new image would have been without the height numbers on the lines anyway and then it would have looked out of place

I don't have the height data because, the way i got the images for the first maps was by generating a height map in  QGIS using a CSV file generated by RROX but, RROX ain't working anymore so i had to use other means to get image for Mesa Plains

there is a LUA script injector im using to enable live edits for UE games and there's a similar line trace LUA script mod what could be modified to do what RROX did, but thats above my head

**Comment by scottanderson** [comment]
Thank you again for your contributions, @illudedPerception. I appreciate the time and effort you’ve dedicated to improving these maps, as well as your willingness to tackle some challenging issues. To ensure alignment with the project’s goals and to streamline future workflows, I’d like to share some feedback and suggestions.

# Map Borders

Instead of moving the border, your image actually needs to be scaled up to fill the same amount of world space as the original did. One way to do that is by calling `.scale(x)` on the image. Alternatively, if you do not change the image size (or pad/crop them differently), the map transform would not require any changes. This approach is what I recommend for simplicity/consistency.

# Raster image challenges

I understand your perspective on adjusting the water color. However, changing multiple aspects of the map simultaneously introduces complexity. I would prefer to be able to address visual enhancements like color adjustments separately from other changes, such as map orientation. With all of this information being baked in to a raster image, it's not possible to edit one thing at a time, or for anyone besides yourself to make these types of edits.

To that end, please consider replacing the raster images with SVG assets. This would allow us to leverage CSS styles for theme-aware color changes (dark mode) without needing to make edits to multiple raster images. Implementing this would make future adjustments simpler and less error-prone, while also enabling theme contributors to make global changes through CSS rather than modifying individual raster assets.

# Topological Data Removal

The removal of this data is of concern because it was a frequently requested feature, I would prefer that we provide the data for the maps where it is available, even if it isn't possible to add for Mesa Plains at this time.

# Mesa Plains Data Collection

I understand the challenges you’ve faced with generating height data for Mesa Plains. These difficulties highlight a broader need for a reproducible build process for map assets. Documenting and sharing your workflow—even if incomplete—would provide a foundation for improving this process and allow others to contribute effectively. I would suggest writing a [README.md](https://github.com/scottanderson/railroad.studio/blob/mainline/README.md) style document with whatever details and insights you are able to provide.

**Comment by illudedPerception** [comment]
> # Map Borders
> 
> Instead of moving the border, your image actually needs to be scaled up to fill the same amount of world space as the original did. One way to do that is by calling `.scale(x)` on the image. Alternatively, if you do not change the image size (or pad/crop them differently), the map transform would not require any changes. This approach is what I recommend for simplicity/consistency.

If i scale the image outside of QGIS to fit the border then the image might not line up with the items generated from the save file as well as it is now, though even now its off by about 2 meters what is fine with the CRS i'm using and this CRS seems to be the most accurate one i have found but there's hundreds if not thousands of them so ~2m +- editing error and the limit on the transformation data length it will be



> To that end, please consider replacing the raster images with SVG assets. This would allow us to leverage CSS styles for theme-aware color changes (dark mode) without needing to make edits to multiple raster images. Implementing this would make future adjustments simpler and less error-prone, while also enabling theme contributors to make global changes through CSS rather than modifying individual raster assets.

i haven't found an way to export them as SVG there are other options what are database based and i don't know how those work and QGIS is not really meant to be used for games, its meant for real life mapology work


> # Topological Data Removal
> 
> The removal of this data is of concern because it was a frequently requested feature, I would prefer that we provide the data for the maps where it is available, even if it isn't possible to add for Mesa Plains at this time.

I will add back the data to the images some day and seems the rotation update is not 100% anyways so i have a bit of time


> # Mesa Plains Data Collection
> 
> I understand the challenges you’ve faced with generating height data for Mesa Plains. These difficulties highlight a broader need for a reproducible build process for map assets. Documenting and sharing your workflow—even if incomplete—would provide a foundation for improving this process and allow others to contribute effectively. I would suggest writing a [README.md](https://github.com/scottanderson/railroad.studio/blob/mainline/README.md) style document with whatever details and insights you are able to provide.

i would but most of the work flow i used before is gone so why share it now ? other methods i'm using now i really don't want to share for other reasons and i don't want to state those reasons here.

QGIS image exporting is based on the programs view port (see images below) what affects the size of the image by a "few" pixels here or there and the transform data is also exported from QGIS according to the image size, that's why the world borders wont match up but atleast then the map image and the SVG overlay of tracks, locomotive and other items matches to a 2m accuracy (the accuracy of the CRS used in QGIS)

this view port results in the size of 4269x4269px at 470DPI
image
but this view port results in an image of 2751x2751px at 470DPI
image

also export options, not including the database ones in other menus and i don't know how to use those
image

**Pull request closed without merging**
